import React from 'react';
import '../css/Cubes.css';

export default function Cubes() {
  return (
<div className="container">
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="trigger" />
  <div className="monitor">
    <div className="camera o-x">
      <div className="camera o-y">
        <div className="camera o-z">
          <div className="vr">
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
            <div className="vr_layer">
              <div className="vr_layer_item" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  )
}
